///
// This file is autogenerated by "figma-design-tokens"!
// Last updated: 5/22/2023, 8:56:20 AM
// If you edit this file, it will be overwritten, next time you run the command.
///

export const heading2xl = {
  fontSize: '24px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1.2083333333333333',
  textTransform: 'none',
};
export const heading3xl = {
  fontSize: '34px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1',
  textTransform: 'none',
};
export const heading4xl = {
  fontSize: '48px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1.0833333333333333',
  textTransform: 'none',
};
export const heading5xl = {
  fontSize: '64px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1',
  textTransform: 'none',
};
export const heading6xl = {
  fontSize: '96px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1',
  textTransform: 'none',
};
export const metaHandwriting = {
  fontSize: '34px',
  fontFamily: 'Handsome Bold',
  fontWeight: '700',
  letterSpacing: 'normal',
  lineHeight: '1',
  textTransform: 'none',
};
export const metaSmnarrow = {
  fontSize: '14px',
  fontFamily: 'Gotham XNarrow',
  fontWeight: '300',
  letterSpacing: 'normal',
  lineHeight: '1.2142857142857142',
  textTransform: 'none',
};
export const paragraphBasebold = {
  fontSize: '16px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1.25',
  textTransform: 'none',
};
export const paragraphBaseboldallcaps = {
  fontSize: '16px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1.25',
  textTransform: 'uppercase',
};
export const paragraphBaselight = {
  fontSize: '16px',
  fontFamily: 'Gentona',
  fontWeight: '300',
  letterSpacing: 'normal',
  lineHeight: '1.1875',
  textTransform: 'none',
};
export const paragraphBaseregular = {
  fontSize: '16px',
  fontFamily: 'Gentona',
  fontWeight: '400',
  letterSpacing: 'normal',
  lineHeight: '1.1875',
  textTransform: 'none',
};
export const paragraphLgbold = {
  fontSize: '18px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1.2222222222222223',
  textTransform: 'none',
};
export const paragraphSmbold = {
  fontSize: '14px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: '0.01em',
  lineHeight: '1.2142857142857142',
  textTransform: 'none',
};
export const paragraphSmlight = {
  fontSize: '14px',
  fontFamily: 'Gentona',
  fontWeight: '300',
  letterSpacing: '0.01em',
  lineHeight: '1.1428571428571428',
  textTransform: 'none',
};
export const paragraphSmregular = {
  fontSize: '14px',
  fontFamily: 'Gentona',
  fontWeight: '400',
  letterSpacing: 'normal',
  lineHeight: '1.1428571428571428',
  textTransform: 'none',
};
export const paragraphXlbold = {
  fontSize: '20px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1.25',
  textTransform: 'none',
};
export const paragraphXsbold = {
  fontSize: '12px',
  fontFamily: 'Gentona',
  fontWeight: '800',
  letterSpacing: 'normal',
  lineHeight: '1.25',
  textTransform: 'none',
};
export const paragraphXsregular = {
  fontSize: '12px',
  fontFamily: 'Gentona',
  fontWeight: '300',
  letterSpacing: 'normal',
  lineHeight: '1.1666666666666667',
  textTransform: 'none',
};
export const paragraphXxsregular = {
  fontSize: '10px',
  fontFamily: 'Gentona',
  fontWeight: '400',
  letterSpacing: 'normal',
  lineHeight: '1.2',
  textTransform: 'none',
};
