///
// This file is autogenerated by "figma-design-tokens"!
// Last updated: 5/22/2023, 8:51:13 AM
// If you edit this file, it will be overwritten, next time you run the command.
///

export const typographyTokens = {
  // FontFamily is: "Gentona"
  heading2xl: [
    '24px',
    {
      lineHeight: '1.2083333333333333',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  heading3xl: [
    '34px',
    {
      lineHeight: '1',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  heading4xl: [
    '48px',
    {
      lineHeight: '1.0833333333333333',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  heading5xl: [
    '64px',
    {
      lineHeight: '1',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  heading6xl: [
    '96px',
    {
      lineHeight: '1',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Handsome Bold"
  metaHandwriting: [
    '34px',
    {
      lineHeight: '1',
      letterSpacing: 'normal',
      fontWeight: 700,
    },
  ],

  // FontFamily is: "Gotham XNarrow"
  metaSmnarrow: [
    '14px',
    {
      lineHeight: '1.2142857142857142',
      letterSpacing: 'normal',
      fontWeight: 300,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphBasebold: [
    '16px',
    {
      lineHeight: '1.25',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphBaseboldallcaps: [
    '16px',
    {
      lineHeight: '1.25',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphBaselight: [
    '16px',
    {
      lineHeight: '1.1875',
      letterSpacing: 'normal',
      fontWeight: 300,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphBaseregular: [
    '16px',
    {
      lineHeight: '1.1875',
      letterSpacing: 'normal',
      fontWeight: 400,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphLgbold: [
    '18px',
    {
      lineHeight: '1.2222222222222223',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphSmbold: [
    '14px',
    {
      lineHeight: '1.2142857142857142',
      letterSpacing: '0.01em',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphSmlight: [
    '14px',
    {
      lineHeight: '1.1428571428571428',
      letterSpacing: '0.01em',
      fontWeight: 300,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphSmregular: [
    '14px',
    {
      lineHeight: '1.1428571428571428',
      letterSpacing: 'normal',
      fontWeight: 400,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphXlbold: [
    '20px',
    {
      lineHeight: '1.25',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphXsbold: [
    '12px',
    {
      lineHeight: '1.25',
      letterSpacing: 'normal',
      fontWeight: 800,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphXsregular: [
    '12px',
    {
      lineHeight: '1.1666666666666667',
      letterSpacing: 'normal',
      fontWeight: 300,
    },
  ],

  // FontFamily is: "Gentona"
  paragraphXxsregular: [
    '10px',
    {
      lineHeight: '1.2',
      letterSpacing: 'normal',
      fontWeight: 400,
    },
  ],
};
